#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /admin/logout

redirect_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/
        permanent: true

redirect_admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/admin
        permanent: true
