#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /admin/logout

redirect_admin_index:
    path: /{_locale}/admin/
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: event_index

redirect_admin:
    path: /admin
    controller: App\Controller\RedirectController::redirectAction

redirect_admin_with_params:
    path: /admin/{path}
    controller: App\Controller\RedirectController::redirectAction
    requirements:
        path: .*

redirect_index:
    path: /{path}
    controller: App\Controller\RedirectController::redirectAction
    requirements:
        path: .*
