main:
    prefix: /{_locale}
    resource: 'routes/main.yaml'
    requirements:
        _locale: en|lt

logout:
    path: /admin/logout

# These redirect paths must be last and in this order!
# All routes redirect form /foo/bar to /en/foo/bar
redirect_admin:
    path: /admin
    controller: App\Controller\RedirectController::redirectAction

redirect_admin_with_params:
    path: /admin/{path}
    controller: App\Controller\RedirectController::redirectAction
    requirements:
        path: .*

redirect_index:
    path: /{path}
    controller: App\Controller\RedirectController::redirectAction
    requirements:
        path: .*
