services:
    _defaults:
        public: true

    test.form_validator: '@App\Service\Form\FormValidator'
    test.url_generator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
    test.event_time_updater: '@App\Service\Event\EventTimeUpdater'
